
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:228 (message)"
      - "/home/cheri/CHERI-zephyr/cmake/modules/kernel.cmake:129 (project)"
      - "/home/cheri/CHERI-zephyr/cmake/modules/zephyr_default.cmake:140 (include)"
      - "/home/cheri/CHERI-zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "/home/cheri/CHERI-zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)"
      - "CMakeLists.txt:7 (find_package)"
    message: |
      The target system is: Generic - 4.1.99 - riscv
      The host system is: Linux - 6.10.14-linuxkit - aarch64
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "/home/cheri/CHERI-zephyr/cmake/modules/kernel.cmake:129 (project)"
      - "/home/cheri/CHERI-zephyr/cmake/modules/zephyr_default.cmake:140 (include)"
      - "/home/cheri/CHERI-zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "/home/cheri/CHERI-zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)"
      - "CMakeLists.txt:7 (find_package)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /home/cheri/cheri/output/sdk/bin/clang 
      Build flags: -march=rv32gcxcheri;-mabi=il32pc64
      Id flags: -c;--target=riscv32-unknown-elf 
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.o"
      
      The C compiler identification is Clang, found in:
        /home/cheri/CHERI-zephyr/samples/fatfs_fuzz_uart/build_write/CMakeFiles/3.28.3/CompilerIdC/CMakeCCompilerId.o
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "/home/cheri/CHERI-zephyr/cmake/modules/kernel.cmake:129 (project)"
      - "/home/cheri/CHERI-zephyr/cmake/modules/zephyr_default.cmake:140 (include)"
      - "/home/cheri/CHERI-zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "/home/cheri/CHERI-zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)"
      - "CMakeLists.txt:7 (find_package)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: /home/cheri/cheri/output/sdk/bin/clang++ 
      Build flags: -march=rv32gcxcheri;-mabi=il32pc64
      Id flags: -c;--target=riscv32-unknown-elf 
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.o"
      
      The CXX compiler identification is Clang, found in:
        /home/cheri/CHERI-zephyr/samples/fatfs_fuzz_uart/build_write/CMakeFiles/3.28.3/CompilerIdCXX/CMakeCXXCompilerId.o
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:1144 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineASMCompiler.cmake:131 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "/home/cheri/CHERI-zephyr/cmake/modules/kernel.cmake:135 (enable_language)"
      - "/home/cheri/CHERI-zephyr/cmake/modules/zephyr_default.cmake:140 (include)"
      - "/home/cheri/CHERI-zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "/home/cheri/CHERI-zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)"
      - "CMakeLists.txt:7 (find_package)"
    message: |
      Checking whether the ASM compiler is GNU using "--version" did not match "(GNU assembler)|(GCC)|(Free Software Foundation)":
      clang version 17.0.0 (https://github.com/CTSRD-CHERI/llvm-project.git 7e122876ee01a7a82585f7674c94f12fc1cc7689)
      Target: aarch64-unknown-linux-gnu
      Thread model: posix
      InstalledDir: /home/cheri/cheri/output/sdk/bin
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:1144 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineASMCompiler.cmake:131 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "/home/cheri/CHERI-zephyr/cmake/modules/kernel.cmake:135 (enable_language)"
      - "/home/cheri/CHERI-zephyr/cmake/modules/zephyr_default.cmake:140 (include)"
      - "/home/cheri/CHERI-zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "/home/cheri/CHERI-zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)"
      - "CMakeLists.txt:7 (find_package)"
    message: |
      Checking whether the ASM compiler is AppleClang using "--version" did not match "(Apple (clang|LLVM) version)":
      clang version 17.0.0 (https://github.com/CTSRD-CHERI/llvm-project.git 7e122876ee01a7a82585f7674c94f12fc1cc7689)
      Target: aarch64-unknown-linux-gnu
      Thread model: posix
      InstalledDir: /home/cheri/cheri/output/sdk/bin
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:1131 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineASMCompiler.cmake:131 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "/home/cheri/CHERI-zephyr/cmake/modules/kernel.cmake:135 (enable_language)"
      - "/home/cheri/CHERI-zephyr/cmake/modules/zephyr_default.cmake:140 (include)"
      - "/home/cheri/CHERI-zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "/home/cheri/CHERI-zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)"
      - "CMakeLists.txt:7 (find_package)"
    message: |
      Checking whether the ASM compiler is Clang using "--version" matched "(clang version)":
      clang version 17.0.0 (https://github.com/CTSRD-CHERI/llvm-project.git 7e122876ee01a7a82585f7674c94f12fc1cc7689)
      Target: aarch64-unknown-linux-gnu
      Thread model: posix
      InstalledDir: /home/cheri/cheri/output/sdk/bin
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/Internal/CheckSourceCompiles.cmake:101 (try_compile)"
      - "/usr/share/cmake-3.28/Modules/Internal/CheckCompilerFlag.cmake:18 (cmake_check_source_compiles)"
      - "/usr/share/cmake-3.28/Modules/CheckCCompilerFlag.cmake:51 (cmake_check_compiler_flag)"
      - "/home/cheri/CHERI-zephyr/cmake/modules/extensions.cmake:2332 (check_c_compiler_flag)"
      - "/home/cheri/CHERI-zephyr/cmake/modules/extensions.cmake:1191 (check_compiler_flag)"
      - "/home/cheri/CHERI-zephyr/cmake/modules/extensions.cmake:2371 (zephyr_check_compiler_flag)"
      - "/home/cheri/CHERI-zephyr/cmake/modules/extensions.cmake:2347 (target_cc_option_fallback)"
      - "/home/cheri/CHERI-zephyr/cmake/modules/extensions.cmake:155 (target_cc_option)"
      - "/home/cheri/CHERI-zephyr/CMakeLists.txt:561 (zephyr_cc_option)"
    directories:
      source: "/home/cheri/CHERI-zephyr/samples/fatfs_fuzz_uart/build_write/CMakeFiles/CMakeScratch/TryCompile-QG6UqZ"
      binary: "/home/cheri/CHERI-zephyr/samples/fatfs_fuzz_uart/build_write/CMakeFiles/CMakeScratch/TryCompile-QG6UqZ"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "/home/cheri/cheri/output/sdk/bin/clang-scan-deps"
      CMAKE_CXX_COMPILER_TARGET: "riscv32-unknown-elf"
      CMAKE_C_COMPILER_TARGET: "riscv32-unknown-elf"
      CMAKE_C_FLAGS: "-march=rv32gcxcheri -mabi=il32pc64 "
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: "-L/home/cheri/cheri/output/sdk/bin/../baremetal/baremetal-riscv32-purecap/lib/ -lclang_rt.builtins-riscv32"
      CMAKE_MODULE_PATH: "/home/cheri/CHERI-zephyr/cmake/modules"
      CMAKE_SYSROOT: "/home/cheri/cheri/output/sdk/baremetal/baremetal-riscv32-purecap/lib"
    buildResult:
      variable: "check_fmacro_prefix_map__home_cheri_CHERI_zephyr_samples_fatfs_fuzz_uart_CMAKE_SOURCE_DIR_C__nostartfiles__nostdlib__isystem___home_cheri_cheri_output_sdk_lib_clang_17_include___fuse_ld_lld"
      cached: true
      stdout: |
        Change Dir: '/home/cheri/CHERI-zephyr/samples/fatfs_fuzz_uart/build_write/CMakeFiles/CMakeScratch/TryCompile-QG6UqZ'
        
        Run Build Command(s): /usr/bin/ninja -v cmTC_70d0b
        [1/2] /home/cheri/cheri/output/sdk/bin/clang --target=riscv32-unknown-elf --sysroot=/home/cheri/cheri/output/sdk/baremetal/baremetal-riscv32-purecap/lib -Dcheck_fmacro_prefix_map__home_cheri_CHERI_zephyr_samples_fatfs_fuzz_uart_CMAKE_SOURCE_DIR_C__nostartfiles__nostdlib__isystem___home_cheri_cheri_output_sdk_lib_clang_17_include___fuse_ld_lld  -march=rv32gcxcheri -mabi=il32pc64  -nostartfiles -nostdlib -isystem "/home/cheri/cheri/output/sdk/lib/clang/17/include" -fuse-ld=lld   -fmacro-prefix-map=/home/cheri/CHERI-zephyr/samples/fatfs_fuzz_uart=CMAKE_SOURCE_DIR -MD -MT CMakeFiles/cmTC_70d0b.dir/src.c.obj -MF CMakeFiles/cmTC_70d0b.dir/src.c.obj.d -o CMakeFiles/cmTC_70d0b.dir/src.c.obj -c /home/cheri/CHERI-zephyr/samples/fatfs_fuzz_uart/build_write/CMakeFiles/CMakeScratch/TryCompile-QG6UqZ/src.c
        clang: warning: argument unused during compilation: '-nostartfiles' [-Wunused-command-line-argument]
        clang: warning: argument unused during compilation: '-fuse-ld=lld' [-Wunused-command-line-argument]
        [2/2] : && /home/cheri/cheri/output/sdk/bin/clang --target=riscv32-unknown-elf --sysroot=/home/cheri/cheri/output/sdk/baremetal/baremetal-riscv32-purecap/lib -march=rv32gcxcheri -mabi=il32pc64  -nostartfiles -nostdlib -isystem "/home/cheri/cheri/output/sdk/lib/clang/17/include" -fuse-ld=lld -L/home/cheri/cheri/output/sdk/bin/../baremetal/baremetal-riscv32-purecap/lib/ -lclang_rt.builtins-riscv32 CMakeFiles/cmTC_70d0b.dir/src.c.obj -o cmTC_70d0b   && :
        clang: warning: argument unused during compilation: '-nostartfiles' [-Wunused-command-line-argument]
        ld.lld: warning: cannot find entry symbol _start; not setting start address
        
      exitCode: 0
...
